# Generated by Django 5.2.14 on 2026-05-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('openai', 'OpenAI'), ('imported', 'Imported'), ('other', 'Other')], default='local', max_length=20)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('content', models.TextField(blank=True)),
                ('markdown_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='media_library.mediaitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('kind', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], default='short', max_length=20)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('openai', 'OpenAI'), ('imported', 'Imported'), ('other', 'Other')], default='local', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('markdown_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='media_library.mediaitem')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='playback.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_progress_entries', to='media_library.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'media_item'), name='unique_playback_progress_per_user_media_item')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('start_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('end_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('content', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='playback.transcript')),
            ],
            options={
                'ordering': ['sequence_number'],
                'constraints': [models.UniqueConstraint(fields=('transcript', 'sequence_number'), name='unique_transcript_segment_sequence')],
            },
        ),
    ]
