# Generated by Django 5.2.14 on 2026-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='kind',
            field=models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed'), ('bullet', 'Bullet')], default='short', max_length=20),
        ),
    ]
