# Generated by Django 5.2.14 on 2026-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenote',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='kind',
            field=models.CharField(choices=[('insight', 'Insight'), ('action', 'Action'), ('reflection', 'Reflection'), ('question', 'Question'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
