# Generated by Django 5.2.14 on 2026-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_notes', '0002_knowledgenote_ai_generated_knowledgenote_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenote',
            name='source_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='summary_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
    ]
