# Generated by Django 5.2.14 on 2026-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_notes', '0003_knowledgenote_source_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenote',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
