# Generated by Django 5.2.14 on 2026-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_notes', '0004_knowledgenote_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenote',
            name='application',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='context_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='core_insight',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='deeper_principle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='first_step',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='problem',
            field=models.TextField(blank=True, default=''),
        ),
    ]
