# Generated by Django 5.2.14 on 2026-05-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_notes", "0005_knowledgenote_application_knowledgenote_context_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeNoteLinkCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("embedding_score", models.FloatField(default=0.0)),
                ("tfidf_score", models.FloatField(default=0.0)),
                ("combined_score", models.FloatField(default=0.0)),
                ("provenance", models.CharField(default="embedding.deeper_principle", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_link_candidates",
                        to="knowledge_notes.knowledgenote",
                    ),
                ),
                (
                    "target_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_link_candidates",
                        to="knowledge_notes.knowledgenote",
                    ),
                ),
            ],
            options={
                "ordering": ["-combined_score", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgenotelinkcandidate",
            constraint=models.UniqueConstraint(
                fields=("source_note", "target_note", "provenance"),
                name="knowledge_note_link_candidate_unique_source_target_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgenotelinkcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_note", models.F("target_note")), _negated=True),
                name="knowledge_note_link_candidate_no_self_link",
            ),
        ),
    ]
