# Generated by Django 5.2.14 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_notes", "0006_knowledgenotelinkcandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgenotelinkcandidate",
            name="rerank_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
