# Generated by Django 5.2.14 on 2026-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media_assets/'),
        ),
    ]
